---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - shophub.devops-siit.io
  resources:
  - wallets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shophub.devops-siit.io
  resources:
  - wallets/finalizers
  verbs:
  - update
- apiGroups:
  - shophub.devops-siit.io
  resources:
  - wallets/status
  verbs:
  - get
  - patch
  - update
