apiVersion: shophub.devops-siit.io/v1
kind: Shop
metadata:
  labels:
    app.kubernetes.io/name: shop-operator
    app.kubernetes.io/managed-by: kustomize
  name: shop-sample
spec:
  displayName: "Sample Shop"
  availability: standard
  databaseType: standard
  wallet:
    address: "0x0000000000000000000000000000000000000000"
  discordChannel:
    channelName: "orders"
    serverID: "123456789012345678"
